[workspace]
members = ["frontend", "backend"]
resolver = "2"

[workspace.dependencies]
futures-util = "0.3.31"
tokio-tungstenite = { version = "0.24.0" }
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0.215", features = ["derive"] }
anyhow = "1.0.94"
chrono = "0.4.39"
