services:
  postgres:
    image: postgres
    container_name: dispatch-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
    image: dispatch-backend
    container_name: dispatch-backend
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
