[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.31"
tokio-tungstenite = { version = "0.24.0", features = ["native-tls"] }
tokio = { version = "1.40.0", features = ["full"] }
uuid = {version = "1.11.0", features = ["v4"] }
