name: Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }} -p frontend
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}